- .eslintignore
- .flowconfig
- .prettierignore
- .travis.yml
- package-lock.json
- package.json
- packages/bpk-docs/package-lock.json
This is setting up a temporary docs build that is deployed alongside our docs pages. For example:
https://backpack.github.io/docs-beta/components/mobile-scroll-container/?platform=web
> Set up travis deploys

- .flowconfig
- .travis.yml
Flow is still complaining 😢 
But everything else works
> Re-enable testing

- CONTRIBUTING.md
Make clearer the instructions for running docs locally.
> [NO-JIRA] Update contributing guide

- docs/src/themeableAttributes.js
> [NO JIRA]: Added buttonThemeAttributes for applying borderRadius

- docs/src/themeableAttributes.js
> [BPK-2477]: Adding new theme attributes to allow gray theming

- docs/src/components/ColorSwatch/ColorSwatch.js
- docs/src/pages/ThemingPage/ThemingPage.js
- docs/src/pages/ThemingPage/theming-page.scss
- package-lock.json
- package.json
Quick-and-dirty colour swatches for the theming page. Will be useful for showing people our new colour theming support.
> [No JIRA] Theme grey swatches

- docs/src/helpers/logo-helper.js
- docs/src/layouts/SideNavLayout/Sidebar.js
- docs/src/pages/HomePage/HomePage.js
> [NO-JIRA] Pride

- docs/src/pages/WebBannerAlertsPage/BannerAlertsPage.js
> [NO-JIRA] Add banner-alert custom icon example to docs

- docs/src/pages/AndroidStarRatingPage/AndroidStarRatingPage.js
- docs/src/pages/AndroidStarRatingPage/index.js
> Added Android Star Rating Page

- package-lock.json
- package.json
> [No JIRA] Upgrade react-svg-loader

- docs/src/layouts/links.js
> [NO-JIRA] Update component platform support meta-data

- docs/src/layouts/SideNavLayout/NavList.scss
- docs/src/layouts/SideNavLayout/NavListFilter.js
> [NO-JIRA] Add android and ios to filter

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/AndroidFloatingActionButtonPage/AndroidFloatingActionButtonPage.js
- docs/src/pages/AndroidFloatingActionButtonPage/index.js
- docs/src/pages/FloatingActionButtonPage/FloatingActionButtonPage.js
- docs/src/pages/FloatingActionButtonPage/index.js
- docs/src/routes/Routes.js
> No jira add floating action button page

- docs/src/constants/redirect-routes.js
- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/IOSTextInputPage/IOSTextInputPage.js
- docs/src/pages/IOSTextInputPage/index.js
- docs/src/pages/TextViewPage/TextViewPage.js
- docs/src/pages/TextViewPage/index.js
- docs/src/routes/Routes.js
> [NO-JIRA] Update docs for new iOS component

- docs/src/constants/redirect-routes.js
- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/IOSTappableLinkLabelPage/IOSTappableLinkLabelPage.js
- docs/src/pages/IOSTappableLinkLabelPage/index.js
- docs/src/pages/IOSTextViewPage/IOSTextViewPage.js
- docs/src/pages/TappableLinkLabelPage/TappableLinkLabelPage.js
- docs/src/pages/TappableLinkLabelPage/index.js
- docs/src/routes/Routes.js
- package-lock.json
> Add docs for Tappable Link Label

- docs/src/pages/IOSTappableLinkLabelPage/IOSTappableLinkLabelPage.js
> [BPK-2596] Add screenshot of alternate style

- docs/src/layouts/links.js
- docs/src/pages/AndroidLinkPage/AndroidLinkPage.js
- docs/src/pages/AndroidLinkPage/index.js
- docs/src/pages/AndroidThemingPage/AndroidThemingPage.js
> Added BpkButtonLink for android.

- docs/src/pages/FormsPage/FormsPage.js
- docs/src/pages/NativeSelectPage/NativeSelectPage.js
- docs/src/pages/SelectPage/SelectPage.js
- docs/src/pages/SelectPage/index.js
- docs/src/pages/WebSelectPage/WebSelectPage.js
- docs/src/pages/WebSelectPage/index.js
- docs/src/routes/Routes.js
> [NO-JIRA] Migrate selects to Selects page

- docs/src/pages/IOSTextPage/IOSTextPage.js
> [BPK-2621] ios labels with multiple font styles

- package-lock.json
- package.json
We received #62. CI was failing so I started doing it manually, but then I noticed that `del` isn't used anywhere, only in the submodules (see search results below). So, may as well remove it.
> [No JIRA] Remove 'del' dependency

- docs/src/layouts/links.js
- docs/src/pages/AndroidTextFieldPage/AndroidTextFieldPage.js
- docs/src/pages/AndroidTextFieldPage/index.js
- docs/src/pages/TextInputPage/TextInputPage.js
+ [ ] [Links platform metadata](/tree/master/docs/src/layouts/links.js)
> [BPK-2734] Added Text Field documentation.

- docs/src/pages/WebButtonsPage/ButtonsPage.js
- docs/src/pages/WebButtonsPage/buttons-page.scss
- package-lock.json
This PR also updates the submodules in the repo too
> [BPK-2743]: Added docs for the Outline button

- docs/src/pages/WebButtonsPage/ButtonsPage.js
- docs/src/pages/WebButtonsPage/buttons-page.scss
+ [x] [Links platform metadata](/tree/master/docs/src/layouts/links.js)
> [NO-JIRA] Fix outline button background

- docs/src/pages/WebNudgersPage/NudgersPage.js
- package-lock.json
**Also updated submodules versions for latest support**
> [BPK-2732]: Added docs for outline nudger

- docs/src/layouts/links.js
- docs/src/pages/IOSStarRatingPage/IOSStarRatingPage.js
- docs/src/pages/IOSStarRatingPage/index.js
- docs/src/pages/StarRatingPage/StarRatingPage.js
> [NO-JIRA] Add ios star rating page

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/AndroidRatingPage/AndroidRatingPage.js
- docs/src/pages/AndroidRatingPage/index.js
- docs/src/pages/RatingPage/RatingPage.js
- docs/src/pages/RatingPage/index.js
- docs/src/routes/Routes.js
> No jira add documentation for rating

- docs/src/layouts/links.js
- docs/src/pages/IOSProgressBarPage/IOSProgressBarPage.js
- docs/src/pages/IOSProgressBarPage/index.js
- docs/src/pages/ProgressPage/ProgressPage.js
> [BPKR-70] Add ios progress bar docs

- docs/src/layouts/links.js
- docs/src/pages/HorizontalNavPage/HorizontalNavPage.js
- docs/src/pages/IOSHorizontalNavPage/IOSHorizontalNavPage.js
- docs/src/pages/IOSHorizontalNavPage/index.js
~Blocked on https://github.com/Skyscanner/backpack-ios/pull/358~
> [BPK-2460] Add iOS Horizontal Navigation page

- docs/src/pages/WebNudgersPage/NudgersPage.js
- docs/src/pages/WebNudgersPage/nudger-page.scss
- package-lock.json
> [BPK-2731]: Added docs for new nudger component

- docs/src/pages/WebTextPage/TextPage.js
> [No JIRA] Add missing `xs` text style for web

- docs/src/components/DocsPageBuilder/DocsPageBuilder.js
- docs/src/components/UsageTable/UsageTable.js
> Fix Do's and Don't's grammar

- docs/src/pages/WebImagesPage/WebImagesPage.js
> [BPK-2781]: Added new docs for BpkImage using BORDER_RADIUS_STYLES

- README.md
> [NO-JIRA] Fix repos link

- docs/src/layouts/links.js
- docs/src/pages/WebRatingPage/Rating.scss
- docs/src/pages/WebRatingPage/WebRatingPage.js
- docs/src/pages/WebRatingPage/index.js
- package-lock.json
- package.json
> Bpk 2708 web rating component

- docs/src/layouts/links.js
- docs/src/pages/DialogsPage/DialogsPage.js
- docs/src/pages/NativeDialogPage/NativeDialogPage.js
- docs/src/pages/NativeDialogPage/index.js
> [BPK-2842] Add docs for RN dialog

- docs/src/pages/DatepickerPage/DatepickerPage.js
- docs/src/pages/HomePage/UpdatedAt.js
- docs/src/pages/WebCalendarPage/WebCalendarPage.js
- docs/src/pages/WebScrollableCalendarPage/test-utils.js
- package-lock.json
- package.json
Closes #92.
Upgraded `date-fns` and fixed errors. 
https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md
> [No Jira] Upgrade `date-fns`

- docs/src/pages/IOSPanelPage/IOSPanelPage.js
> [BPK-2884] Add ios elevated style panel screenshots

- docs/src/pages/NativeChipsPage/NativeChipsPage.js
> [BPK-2868]: Added docs for outline docs

- docs/src/themeableAttributes.js
- package-lock.json
> [BPK-2888]: Added starRating theming attributes to themeAttributes file

- docs/src/pages/FormsPage/FormsPage.js
> [NO-JIRA] Update docs to showcase new invalid form elements

- docs/src/themeableAttributes.js
- package-lock.json
> [NO JIRA]: Adding the new theme attributes following Backpack release

- docs/src/pages/WebRatingPage/WebRatingPage.js
- package-lock.json
> [BPK-2811]: Updated docs to show different rating sizes

- docs/src/pages/WebSelectPage/WebSelectPage.js
> [NO-JIRA] Improve selects page

- docs/src/pages/FormsPage/FormsPage.js
- docs/src/pages/WebSelectPage/WebSelectPage.js
> [NO-JIRA] Use label props on select page

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/FormsPage/FormsPage.js
- docs/src/pages/RadioButtonPage/RadioButtonPage.js
- docs/src/pages/RadioButtonPage/index.js
- docs/src/pages/WebRadioButtonPage/WebRadioButtonsPage.js
- docs/src/pages/WebRadioButtonPage/index.js
- docs/src/routes/Routes.js
> [BPK-2693] [BPK-2693] Split radio buttons into separate page

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/FormLabelPage/FormLabelPage.js
- docs/src/pages/FormLabelPage/index.js
- docs/src/pages/FormsPage/FormsPage.js
- docs/src/pages/WebFormLabelPage/WebFormLabelPage.js
- docs/src/pages/WebFormLabelPage/index.js
- docs/src/routes/Routes.js
> [BPK-2693] Split out form-label page

- docs/src/pages/WebRatingPage/Rating.scss
- docs/src/pages/WebRatingPage/WebRatingPage.js
- package-lock.json
> [BPK-2812]: Added docs for vertical rating

- docs/src/layouts/links.js
- docs/src/pages/IOSRatingPage/IOSRatingPage.js
- docs/src/pages/IOSRatingPage/index.js
> [BPK-2710] Add iOS rating docs

- docs/src/pages/WebRatingPage/Rating.scss
- docs/src/pages/WebRatingPage/WebRatingPage.js
- package-lock.json
> [BPK-2938]: Adding title only docs

- docs/src/layouts/links.js
> [NO-JIRA] Fix form validation link

- docs/src/pages/AndroidThemingPage/AndroidThemingPage.js
- docs/src/pages/IOSThemingPage/IOSThemingPage.js
- docs/src/pages/ThemingPage/ThemingPage.js
> [NO-JIRA] Remove lists of themeable components

- docs/src/layouts/links.js
- docs/src/pages/IOSToastPage/IOSToastPage.js
- docs/src/pages/IOSToastPage/index.js
> [BPK-2680] [BPK-2680] Add iOS toast page

- docs/src/pages/IOSRatingPage/IOSRatingPage.js
- docs/src/pages/RatingPage/RatingPage.js
> [NO-JIRA] Enable iOS rating page

- docs/src/layouts/links.js
- docs/src/pages/AndroidStarRatingInteractivePage/AndroidStarRatingInteractivePage.js
- docs/src/pages/IOSStarRatingInteractivePage/IOSStarRatingInteractivePage.js
- docs/src/pages/IOSStarRatingInteractivePage/index.js
- docs/src/pages/WebStarRatingInteractivePage/WebStarRatingInteractivePage.js
- docs/src/pages/WebStarRatingInteractivePage/index.js
> [NO-JIRA] Add interactive star rating pages for ios and web

- docs/src/themeableAttributes.js
> [NO-JIRA] Remove unused theme attribute

- docs/src/components/PresentationBlock/PresentationBlock.scss
- docs/src/layouts/SideNavLayout/NavList.scss
- docs/src/layouts/SideNavLayout/SectionsList.scss
- docs/src/layouts/SideNavLayout/Sidebar.scss
- docs/src/layouts/SideNavLayout/_common.scss
- docs/src/pages/WebNavigationBarPage/AirlineLogo.scss
> [NO-JIRA] Update sidenav default colours

- docs/src/components/ColorSwatch/ColorSwatch.js
- docs/src/components/ColorSwatch/color-swatch.scss
- docs/src/pages/ColorsPage/ColorsPage.js
- package-lock.json
> [NO JIRA]: Adding new colours to the Colours docs page

- docs/src/components/AlternatingPageContent/AlternatingPageContent.scss
- docs/src/components/ColorSwatch/color-swatch.scss
- docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.scss
- docs/src/components/DocsPageBuilder/DocsPageBuilder.scss
- docs/src/components/Footer/Footer.scss
- docs/src/components/Header/HamburgerButton.scss
- docs/src/components/Header/Header.scss
- docs/src/components/HeroSection/HeroSection.scss
- docs/src/components/HomePageCard/HomePageCard.scss
- docs/src/components/IconSearchApp/IconSearchResult.scss
- docs/src/components/InfoPageBuilder/InfoPageBuilder.scss
- docs/src/components/IntroBlurb/IntroBlurb.scss
- docs/src/components/PageHead/PageHead.scss
- docs/src/components/PresentationBlock/PresentationBlock.scss
- docs/src/components/UsageTable/UsageTable.scss
- docs/src/layouts/DefaultLayout/default-layout.scss
- docs/src/layouts/SideNavLayout/MainHeroImage.scss
- docs/src/layouts/SideNavLayout/NavList.scss
- docs/src/layouts/SideNavLayout/SectionsList.scss
- docs/src/layouts/SideNavLayout/_common.scss
- docs/src/pages/AlignmentPage/AlignmentPage.js
- docs/src/pages/BreakpointsPage/breakpoints-page.scss
- docs/src/pages/GridDemoPages/grid-demo-pages.scss
- docs/src/pages/HomePage/home-page.scss
- docs/src/pages/InfiniteScrollPage/InfiniteScrollPage.scss
- docs/src/pages/MobileScrollContainerPage/BlockExample.scss
- docs/src/pages/NavigationStackPage/NavigationStackPage.scss
- docs/src/pages/TooltipsPage/TooltipsPage.js
- docs/src/pages/WebBadgePage/badge-page.scss
- docs/src/pages/WebNavigationBarPage/NavigationBarPage.scss
> Remove old colours from the docs

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/FlarePage/FlarePage.js
- docs/src/pages/FlarePage/index.js
- docs/src/pages/WebFlarePage/Flare.scss
- docs/src/pages/WebFlarePage/WebFlarePage.js
- docs/src/pages/WebFlarePage/index.js
- docs/src/routes/Routes.js
- package-lock.json
- package.json
> Adding flare docs

- docs/src/layouts/links.js
- docs/src/pages/IOSFlarePage/IOSFlarePage.js
- docs/src/pages/IOSFlarePage/index.js
> [NO-JIRA] Document ios flare

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/BottomSheetPage/BottomSheetPage.js
- docs/src/pages/BottomSheetPage/index.js
- docs/src/pages/IOSBottomSheetPage/IOSBottomSheetPage.js
- docs/src/pages/IOSBottomSheetPage/index.js
- docs/src/routes/Routes.js
- package-lock.json
> [NO-JIRA] Document ios bottom sheet

- docs/src/constants/redirect-routes.js
- docs/src/constants/routes.js
- docs/src/layouts/GuidelinesLayout/GuidelinesLayout.js
- docs/src/layouts/GuidelinesLayout/index.js
- docs/src/layouts/SideNavLayout/SectionsList.js
- docs/src/layouts/links.js
- docs/src/pages/HomePage/HomePage.js
- docs/src/routes/Routes.js
> Bpk 3068 rename styleguide

- docs/src/components/NavigationFooter/NavigationFooter.scss
- docs/src/pages/StrategyPage/StrategyPage.js
> Fix small strategy page bugs

- docs/src/components/ColorSwatch/ColorSwatch.js
- docs/src/pages/ThemingPage/ThemingPage.js
- docs/src/pages/ThemingPage/theming-page.scss
> [NO-JIRA] Fix theming page

- docs/src/pages/IOSBadgePage/IOSBadgePage.js
- docs/src/pages/IOSBottomSheetPage/IOSBottomSheetPage.js
- docs/src/pages/IOSButtonPage/IOSButtonPage.js
- docs/src/pages/IOSDialogPage/IOSDialogPage.js
- docs/src/pages/IOSIconPage/IOSIconPage.js
- docs/src/pages/IOSSwitchPage/IOSSwitchPage.js
- docs/src/pages/IOSTextInputPage/IOSTextInputPage.js
- docs/src/pages/IOSTextViewPage/IOSTextViewPage.js
> [NO-JIRA] Show iOS dark mode components

- docs/src/layouts/links.js
- docs/src/pages/IOSNavigationBarPage/IOSNavigationBarPage.js
- docs/src/pages/IOSNavigationBarPage/index.js
- docs/src/pages/NavigationBarPage/NavigationBarPage.js
> [NO-JIRA] Add iOS navigation bar page

- docs/src/pages/IOSCardPage/IOSCardPage.js
- docs/src/pages/IOSHorizontalNavPage/IOSHorizontalNavPage.js
- docs/src/pages/IOSRatingPage/IOSRatingPage.js
- docs/src/pages/IOSTappableLinkLabelPage/IOSTappableLinkLabelPage.js
> [NO-JIRA] More dark mode screenshots

- docs/src/layouts/links.js
> [NO-JIRA] Correctly sort links

- docs/src/pages/PhoneInputPage/PhoneInputPage.js
- package-lock.json
- package.json
> [BPK-3168] Add masked phone input example

- docs/src/pages/ColorsPage/ColorsPage.js
> Adding a link to the colours sassdoc

- docs/src/pages/IOSDialogPage/IOSDialogPage.js
> [NO-JIRA] Document flare-view dialog

- docs/src/pages/IOSSpinnerPage/IOSSpinnerPage.js
> [NO-JIRA] Add iOS dark-mode spinner screenshot to docs

- docs/src/components/DocsPageBuilder/DocsPageBuilder.js
- docs/src/components/PageHead/PageHead.js
- docs/src/layouts/links.js
- docs/src/pages/NativeRatingPage/NativeRatingPage.js
- docs/src/pages/NativeRatingPage/index.js
- docs/src/pages/RatingPage/RatingPage.js
> [BPK-3292] Add docs for the rating component on RN

- docs/src/pages/AndroidFlarePage/AndroidFlarePage.js
- docs/src/pages/AndroidFlarePage/index.js
- docs/src/pages/FlarePage/FlarePage.js
> [BPK-3037] Add Android flare page

- .flowconfig
- docs/src/components/ContentGrid/ContentGrid.js
- docs/src/components/GuidelinesBuilder/GuidelinesPageBuilder.js
- docs/src/components/HeroSection/HeroSection.js
- docs/src/components/HeroSection/index.js
- package-lock.json
- package.json
Gone from `0.101` to `0.111`. I haven't yet gone to `0.112` because it surfaces errors coming from the main Backpack component dependencies.
> [No JIRA] Upgrade Flow

- docs/src/layouts/SideNavLayout/SideNavLayout.scss
> [BPK-3353] Fix sidenav layout overflow on mobile devices

- docs/src/components/ColorSwatch/ColorSwatch.js
> [NO-JIRA] Fix missing PMS value

- docs/src/layouts/SideNavLayout/NavListFilter.js
It bugs me that it doesn't say "react native", it'll just confuse people and it's not consistent with the horizontal nav we have on component pages
> [No JIRA] Fix native label

- docs/src/pages/NativeFlatListPage/NativeFlatListPage.js
- docs/src/pages/NativeSectionListPage/NativeSectionListPage.js
> [BPK-3324] Update FlatList and SectionList pages to include search

- docs/src/components/PageSearch/PageSearch.js
- docs/src/layouts/SideNavLayout/NavList.js
- docs/src/layouts/SideNavLayout/NavList.scss
Added the search field to the sidebar! Design approved by Will 🎉 
Small convenience - press `Cmd` + `Ctrl` + `S` to focus the search field and scroll to the top of the page (so it's in view).
Very quick and dirty, it's just a power user feature. We'll probably use it more than anybody :P
> [No JIRA] Add search to sidebar

- docs/src/pages/IOSToastPage/IOSToastPage.js
> [NO-JIRA] Add toast dark mode screenshot

- docs/src/components/PageSearch/PageSearch.js
- docs/src/layouts/SideNavLayout/NavList.js
To make the behaviour consistent with when one of the listed items is selected
> [NO-JIRA] Close mobile navigation when autosuggest item is selected

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/StatusPage/StatusPage.js
- docs/src/pages/StatusPage/content/androidStatus.md
- docs/src/pages/StatusPage/content/iosStatus.md
- docs/src/pages/StatusPage/content/nativeStatus.md
- docs/src/pages/StatusPage/content/webStatus.md
- docs/src/pages/StatusPage/index.js
- docs/src/routes/Routes.js
Adding a new Backpack status page to display all of Backpack platforms.
This inital idea/design has been approved for use by Backpack design
> Adding new status page

- docs/src/components/ColorSwatch/DynamicColorSwatch.js
- docs/src/components/ColorSwatch/color-swatch.scss
- docs/src/components/ColorSwatch/index.js
- docs/src/pages/ColorsPage/ColorsPage.js
- docs/src/pages/ColorsPage/dynamicColors.js
> [BPK-3314] [BPK-3314] [BPK-3314] Add dynamic colours

- docs/src/pages/ColorsPage/colors.js
- docs/src/pages/ColorsPage/dynamicColors.js
> [BPK-3314] [BPK-3314] Remove unnecessary swatch borders

- docs/src/helpers/logo-helper.js
> [NO-JIRA] Extend christmas cheer

- docs/src/pages/StatusPage/content/androidStatus.md
- docs/src/pages/StatusPage/content/iosStatus.md
> Fixing url to be https

- docs/src/pages/IOSCalendarPage/IOSCalendarPage.js
> [NO-JIRA] Document iOS calendar with custom colours

- webpack.config.babel.js
> [NO-JIRA] Simplify process.env webpack logic

- docs/src/pages/DatepickerPage/DatepickerPage.js
> [BPK-3605] Format date for calendar correctly

- docs/src/pages/ColorsPage/ColorsPage.js
> [NO-JIRA] Add dynamic colour blurrb

- docs/src/layouts/SideNavLayout/MainHeroImage.js
- docs/src/layouts/SideNavLayout/Sidebar.js
> [NO-JIRA] Add aria expanded to docs menu button

- docs/src/pages/HomePage/HomePage.js
> [BPK-3729] Reorder home page

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/AndroidBottomNavPage/AndroidBottomNavPage.js
- docs/src/pages/AndroidBottomNavPage/index.js
- docs/src/pages/BottomNavPage/BottomNavPage.js
- docs/src/pages/BottomNavPage/index.js
- docs/src/routes/Routes.js
> No jira add bpk bottom nav

- docs/src/components/PageSearch/PageSearch.js
- docs/src/constants/external-routes.js
- docs/src/layouts/links.js
- docs/src/pages/HomePage/HomePage.js
> [NO-JIRA] Support page search blank misc links

- docs/src/pages/NativePickerPage/NativePickerPage.js
> [BPK-3730] Add usage guidelines for picker component

- docs/src/components/DocsPageWrapper/DocsPageWrapper.js
> [NO-JIRA] Select design by default if available

- docs/src/bag-check-bookmarklet/index.js
- docs/src/components/DocsPageWrapper/DocsPageWrapper.js
- docs/src/layouts/links.js
- docs/src/pages/AccessibilityPage/AccessibilityPage.js
- docs/src/pages/ColorsPage/ColorsPage.js
- docs/src/pages/CopywritingPage/CopywritingPage.js
- docs/src/pages/DesignPlaceholderPage/DesignPlaceholderPage.js
- docs/src/pages/DesignPlaceholderPage/index.js
- docs/src/pages/GraphicDevicesPage/GraphicDevicesPage.js
- docs/src/pages/IconographyPage/IconographyPage.js
- docs/src/pages/IllustrationPage/IllustrationPage.js
- docs/src/pages/InUsePage/InUsePage.js
- docs/src/pages/LogoPage/LogoPage.js
- docs/src/pages/ModalsPage/ModalsPage.js
- docs/src/pages/PhotographyPage/PhotographyPage.js
- docs/src/pages/ShadowsGuidelinesPage/ShadowsPage.js
- docs/src/pages/StrategyPage/StrategyPage.js
- docs/src/pages/ToneOfVoicePage/ToneOfVoicePage.js
- docs/src/pages/TypographyPage/TypographyPage.js
- scripts/npm/create-component.js
Unfortunately the linter changed a lot of these files, so I'll list which ones need looking at:
* `DocsPageWrapper.js`
* `DesignPlaceholderPage.js`
I tweaked the logic so that design is 'last' in the hierarchy of pages to automatically show users. I think this is the right decision as it means users won't see that page unless they explicitly go to it, which seems more useful. We don't want to be in people's face, just have it there as a small thing.
I made up the text we show - very happy to change it if people have a better suggestion. I wasn't sure what to put.
> [BPK-3750] Add placeholder page for design tab

- docs/src/layouts/links.js
- docs/src/pages/FlarePage/FlarePage.js
- docs/src/pages/NativeFlarePage/NativeFlarePage.js
- docs/src/pages/NativeFlarePage/index.js
> [BPK-3757] Add RN Flare page

- docs/src/pages/NativeFlarePage/NativeFlarePage.js
> [BPK-3748] Update docs for flare on iOS in RN

- docs/src/components/Analytics/AnalyticsContainer.test.js
- docs/src/components/Analytics/__snapshots__/AnalyticsContainer.test.js.snap
- docs/src/helpers/google-analytics-helper.js
> [NO-JIRA] Fix spelling

- docs/src/pages/NativeBadgePage/NativeBadgePage.js
> [BPK-3802] Docs for new badge prop

- docs/src/pages/TypesettingPage/TypesettingPage.js
> [NO-JIRA] Fix typesetting info

- docs/src/pages/AndroidFlarePage/AndroidFlarePage.js
> [BPK-3808] Add flare pointing up for Android

- docs/src/pages/IOSFlarePage/IOSFlarePage.js
> [BPK-3809] iOS add flare pointing up docs

- docs/src/pages/NativeSnackbarPage/NativeSnackbarPage.js
- docs/src/pages/NativeSnackbarPage/index.js
> [BPK-3301] Add RN Snackbar page

- docs/src/pages/NativeFlarePage/NativeFlarePage.js
> [BPK-3810 and BPK-3811] Add docs for flare pointing up

- docs/src/pages/NativeChipsPage/NativeChipsPage.js
> [BPK-3838]: Add chip icon docs

- docs/src/pages/IOSFlarePage/IOSFlarePage.js
> [BPK-3812] Document rounded flare

- docs/src/helpers/tokens-helper.js
- docs/src/pages/TypesettingPage/TypesettingPage.js
> [No JIRA] Remove native line heights

- docs/src/layouts/links.js
> [NO-JIRA] Fix snackbar metadata

- docs/src/pages/IOSHorizontalNavPage/IOSHorizontalNavPage.js
> [NO-JIRA] Document new horizontal navigation configurations

- docs/src/pages/IOSRatingPage/IOSRatingPage.js
> [NO-JIRA] Add vertical rating screenshots

- docs/src/layouts/links.js
- docs/src/pages/AndroidBarChartPage/AndroidBarChartPage.js
- docs/src/pages/AndroidBarChartPage/index.js
- docs/src/pages/BarchartsPage/BarchartsPage.js
> Add android docs for bpk barchart

- docs/src/pages/AndroidCalendarPage/AndroidCalendarPage.js
- docs/src/pages/NativeCalendarPage/NativeCalendarPage.js
Adding Coloured Calendar examples
> [BPK-3465]: Added coloured calendar screenshots

- docs/src/layouts/links.js
- docs/src/pages/BarchartsPage/BarchartsPage.js
- docs/src/pages/IOSBarChartPage/IOSBarChartPage.js
- docs/src/pages/IOSBarChartPage/index.js
> [BPK-3812] [BPK-3812] Document iOS bar chart

- docs/src/layouts/links.js
- docs/src/pages/SwitchPage/SwitchPage.js
- docs/src/pages/WebSwitchPage/WebSwitchPage.js
- docs/src/pages/WebSwitchPage/index.js
- package-lock.json
- package.json
> [BPK-3954] Docs for web switch component

- docs/src/pages/NativeRatingPage/NativeRatingPage.js
Tbh probably should have just done this to master 🤷‍♂️
> [BPK-3865] Remove beta warning from RN rating

- docs/src/pages/WebLinksPage/LinksPage.js
- docs/src/pages/WebLinksPage/LinksPage.scss
- docs/src/pages/WebSectionListPage/SectionListPage.js
This is what I did for the link one:
> [BPK-3862] Better docs for sectionlist and links

- docs/src/pages/TablesPage/TablesPage.js
- package-lock.json
- package.json
> [BPK-3931] Document datatable component

- docs/src/pages/IOSChipPage/IOSChipPage.js
> [NO-JIRA] Add outline chip for iOS

- docs/src/layouts/links.js
- docs/src/pages/NativeLinkPage/NativeLinkPage.js
- docs/src/pages/NativeLinkPage/index.js
> [BPK-2527]: Added text link component docs

- docs/src/components/HomePageCard/HomePageCard.js
- docs/src/layouts/SideNavLayout/SectionsList.js
- docs/src/layouts/SideNavLayout/Sidebar.js
- docs/src/pages/HomePage/HomePage.js
> [NO-JIRA] Aria fixes

- package-lock.json
- package.json
- webpack.config.babel.js
> [No Jira] Update copy-webpack-plugin dependency

- docs/src/pages/WebHorizontalNavPage/HorizontalNavPage.js
- package-lock.json
- package.json
> [BPK-4077] Add example of light horizontal nav for web

- docs/src/components/IconSearchApp/IconSearchApp.js
- docs/src/components/IconSearchApp/IconSearchResult.js
- docs/src/components/IconSearchApp/IconSearchResults.js
- docs/src/pages/IconsDesignPage/IconDesignPage.js
> [BPK-4078] Add messaging about different sized icon availability

- docs/src/pages/WebProgressPage/ProgressPage.js
> [BPK-4086] Add usage guidelines for progress bar

- docs/src/pages/AndroidChipPage/AndroidChipPage.js
> [BPK-3964]: Add outline chip

- docs/src/pages/WebButtonsPage/ButtonsPage.js
> [NO-JIRA] Add button do-dont guidance

- docs/src/components/PageSearch/search.js
> [NO-JIRA] Fix Fuse usage in IE and Edge

- docs/src/constants/routes.js
- docs/src/routes/Routes.js
> [NO-JIRA] Fix 404 page

- docs/src/layouts/links.js
- docs/src/pages/IOSSnackbarPage/IOSSnackbarPage.js
- docs/src/pages/IOSSnackbarPage/index.js
- docs/src/pages/SnackbarPage/SnackbarPage.js
> [BPK-3869] Document iOS Snackbar

- docs/src/constants/routes.js
- docs/src/pages/NotFoundPage/not-found-page.scss
- docs/src/routes/Routes.js
- webpack.config.babel.js
Ok this should actually work, as it will create `/404.html` instead of `/404/index.html`
> [NO-JIRA] Fix 404 2

- docs/src/pages/MapPage/MapPage.js
> [BPK-4152] Add documentation for RN price markers

- .flowconfig
- docs/src/components/DocsPageBuilder/BpkDoDont.js
- docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.js
- docs/src/components/GuidelinesBuilder/GuidelinesPageBuilder.js
- docs/src/components/HomePageCard/HomePageCard.js
- docs/src/components/PageHead/PageHead.js
- docs/src/layouts/SideNavLayout/NavList.js
- docs/src/pages/BagCheckPage/BagCheckPage.js
- docs/src/pages/MobileScrollContainerPage/BlockExample.js
- docs/src/pages/ModalsPage/ModalsPage.js
- docs/src/pages/NavigationStackPage/page-components.js
- docs/src/pages/PhoneInputPage/PhoneInputPage.js
- docs/src/pages/WebDialogPage/DialogExamples.js
- docs/src/pages/WebNudgersPage/NudgersPage.js
- package.json
> [no jira]: Fixing Flow 0.132.0

- docs/src/components/ComponentPage/AndroidComponentPage.js
- docs/src/pages/AndroidBadgePage/AndroidBadgePage.js
- docs/src/pages/AndroidBarChartPage/AndroidBarChartPage.js
- docs/src/pages/AndroidBottomNavPage/AndroidBottomNavPage.js
- docs/src/pages/AndroidButtonPage/AndroidButtonPage.js
- docs/src/pages/AndroidCalendarPage/AndroidCalendarPage.js
- docs/src/pages/AndroidCardPage/AndroidCardPage.js
- docs/src/pages/AndroidCheckboxPage/AndroidCheckboxPage.js
- docs/src/pages/AndroidChipPage/AndroidChipPage.js
- docs/src/pages/AndroidDialogPage/AndroidDialogPage.js
- docs/src/pages/AndroidFlarePage/AndroidFlarePage.js
- docs/src/pages/AndroidFloatingActionButtonPage/AndroidFloatingActionButtonPage.js
- docs/src/pages/AndroidHorizontalNavPage/AndroidHorizontalNavPage.js
- docs/src/pages/AndroidNavBarPage/AndroidNavBarPage.js
- docs/src/pages/AndroidPanelPage/AndroidPanelPage.js
- docs/src/pages/AndroidRatingPage/AndroidRatingPage.js
- docs/src/pages/AndroidSnackbarPage/AndroidSnackbarPage.js
- docs/src/pages/AndroidSpinnerPage/AndroidSpinnerPage.js
- docs/src/pages/AndroidStarRatingPage/AndroidStarRatingPage.js
- docs/src/pages/AndroidSwitchPage/AndroidSwitchPage.js
- docs/src/pages/AndroidTextFieldPage/AndroidTextFieldPage.js
- docs/src/pages/AndroidTextPage/AndroidTextPage.js
- docs/src/pages/AndroidToastPage/AndroidToastPage.js
> [BPK-4144] Add useful links to Android component pages

- docs/src/pages/WebTextInputPage/WebTextInputPage.js
> [NO-JIRA] Update input usage advice and examples

- docs/src/pages/NativeMapPage/NativeMapPage.js
> [BPK-4178]: New map markers docs

- docs/src/pages/AccordionsPage/AccordionsPage.js
> [NO-JIRA] Add airports icon to accordion example

- docs/src/components/ApidocLink/ApidocLink.js
- docs/src/components/ComponentPage/AndroidComponentPage.js
- docs/src/components/ComponentPage/IOSComponentPage.js
- docs/src/components/ComponentPage/NativeComponentPage.js
- docs/src/components/ComponentPage/WebComponentPage.js
- docs/src/components/DocsPageBuilder/ComponentScreenshots.js
- docs/src/components/DocsPageBuilder/ComponentVideos.js
- docs/src/components/DocsPageBuilder/DocsPageBuilder.js
- docs/src/components/DocsPageBuilder/TokenSwitcher.js
- docs/src/components/HomePageCard/HomePageCard.js
- docs/src/components/IconSearchApp/IconSearchForm.js
- docs/src/components/IconSearchApp/IconSearchResult.js
- docs/src/components/IconSearchApp/IconSearchResults.js
- docs/src/layouts/SideNavLayout/SectionsList.js
- docs/src/layouts/SideNavLayout/Sidebar.js
- docs/src/pages/ColorsPage/ColorChart.js
- docs/src/pages/GraphicDevicesPage/overviewRow.js
- docs/src/pages/HomePage/HomePage.js
- docs/src/pages/IconsDesignPage/IconDesignPage.js
- docs/src/pages/LogoPage/LogoPage.js
- docs/src/pages/NativeHorizontalNavPage/NativeHorizontalNavPage.js
- docs/src/pages/NotFoundPage/NotFoundPage.js
- docs/src/pages/ShadowsGuidelinesPage/ShadowsPage.js
- package-lock.json
- package.json
Methodology:
- Fix most errors
- Ignore all the image ones, there are too many of them and it's not worth the time investment to fix them. I did try updating some to use `BpkImage` but they broke.
> [No Jira] Update eslint-config-skyscanner

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/AndroidOverlayPage/AndroidOverlayPage.js
- docs/src/pages/AndroidOverlayPage/index.js
- docs/src/pages/OverlayPage/OverlayPage.js
- docs/src/pages/OverlayPage/index.js
- docs/src/routes/Routes.js
> Added Android Overlay page.

- package-lock.json
- package.json
Removing this dependency as its bundled within `stylelint-config-skyscanner`
> [no jira]: Removing stylelint due to bundling

- docs/src/layouts/links.js
- docs/src/pages/WebOverlayPage/WebOverlayPage.js
- docs/src/pages/WebOverlayPage/WebOverlayPage.scss
- docs/src/pages/WebOverlayPage/index.js
- package-lock.json
- package.json
> [BPK-4227] Add web overlay docs

- docs/src/components/MarkdownPage/MarkdownPage.js
- docs/src/components/MarkdownPage/MarkdownPage.scss
- docs/src/components/MarkdownPage/index.js
- docs/src/pages/StatusPage/Content.md
- docs/src/pages/StatusPage/content/androidStatus.md
- docs/src/pages/StatusPage/content/backpackNodeSassStatus.md
- docs/src/pages/StatusPage/content/backpackReactScriptsStatus.md
- docs/src/pages/StatusPage/content/eslintConfigSkyscannerStatus.md
- docs/src/pages/StatusPage/content/eslintPluginBackpackStatus.md
- docs/src/pages/StatusPage/content/iosStatus.md
- docs/src/pages/StatusPage/content/nativeStatus.md
- docs/src/pages/StatusPage/content/webStatus.md
- package.json
Proof of concept of `MarkdownPage`, with the status page migrated to use it.
**Why are `title` and `subtitle` props instead of just coming from the markdown?**
We need to know the title so we can set `window.title`. I tried pulling it out automatically but it's hacky so I decided to be explicit instead. This way also allows us to put that nice white area at the top with the title and subtitle. When we expand this PoC to do some snazzy automatic generation stuff, we should be able to pull these out of front matter or something to set them, so it should scale.
**The background alternating colours don't work with these**
Nope. YAGNI.
> [BPK-4252] Add MarkdownPage and migrate status page to use it

- docs/src/components/DocsPageBuilder/ComponentScreenshots.scss
> [NO-JIRA] Fix screenshot max-width

- .github/workflows/ci.yml
> [NO-JIRA] Fix docs deploy location

- docs/src/components/AlternatingPageContent/AlternatingPageContent.js
- docs/src/components/AlternatingPageContent/AlternatingPageContent.scss
- docs/src/components/ComponentPage/ComponentPage.js
- docs/src/components/ComponentPage/ComponentPage.scss
- docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.js
- docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.scss
- docs/src/components/DocsPageBuilder/DocsPageBuilder.scss
- docs/src/components/GuidelinesBuilder/GuidelinesPageBuilder.scss
- docs/src/components/Heading/Heading.scss
- docs/src/components/PresentationBlock/PresentationBlock.scss
- docs/src/pages/InfiniteScrollPage/InfiniteScrollPage.scss
- docs/src/pages/NavigationStackPage/NavigationStackPage.scss
> [NO-JIRA] WIP - Kill alternating colours

- docs/src/static-pages/status.md
> [NO-JIRA] Fix Backpack status badge

- .github/workflows/ci.yml
> [NO-JIRA] test CI nv

- docs/src/pages/IconPage/IconPage.js
> [NO JIRA]: Adding link to icon list in intro blurb

- docs/src/static-pages/status.md
> Updating Badges

- docs/src/pages/components/Rating/IOSRatingPage.js
> [BPK-4111] Pill rating docs

- docs/src/pages/components/Chips/ChipsPage.scss
- docs/src/pages/components/Chips/WebChipsPage.js
Not including screenshots because I want to know what you think about what I've added to the page and how it works.
> [BPK-3604] Document chip aria-live region

- docs/src/pages/components/BannerAlert/WebBannerAlertPage.js
- docs/src/pages/components/BannerAlert/bpk-banner-alerts-page.scss
> [BPK-3614] Improve banner-alert docs

- docs/src/helpers/logo-helper.js
> [NO-JIRA] Allow Christmas logo to take precedence

- docs/src/static-pages/accessibility.md
Updating the docs with the latest version of the guidelines
> [BPK-4300]: Updating engineering A11y docs

- docs/src/components/AriaLiveDemo/AriaLiveDemo.js
- docs/src/components/AriaLiveDemo/AriaLiveDemo.scss
- docs/src/components/AriaLiveDemo/index.js
- docs/src/pages/components/AriaLive/WebAriaLivePage.js
- docs/src/pages/components/BannerAlert/WebBannerAlertPage.js
- docs/src/pages/components/BannerAlert/bpk-banner-alerts-page.scss
- docs/src/pages/components/Chips/ChipsPage.scss
- docs/src/pages/components/Chips/WebChipsPage.js
> [NO-JIRA] Add aria-live demo component

- docs/src/components/MarkdownPage/AdditionalLinks.js
- docs/src/components/MarkdownPage/MarkdownPage.js
- docs/src/components/MarkdownPage/MarkdownPage.scss
- docs/src/pages/components/Text/AndroidText.mdx
- docs/src/pages/components/Text/NativeText.mdx
- docs/src/pages/components/Text/iOSText.mdx
I tried putting an icon in the edit button but it looked terrible (see below)
> [BPK-4331] Move additional links to the top of the page

- docs/src/layouts/SideNavLayout/MenuToggle.scss
> [No Jira] Move menu button to accomodate edit button

- docs/src/static-pages/principles.mdx
> [NO-JIRA] Link to accessibility guidelines

- .eslintrc
- .flowconfig
- babel.config.js
- docs/src/components/InfoPageBuilder/InfoPageBuilder.js
- docs/src/layouts/SideNavLayout/NavList.js
- docs/src/pages/components/Accordions/WebAccordionsPage.js
- docs/src/pages/components/Alert/AlertPage.js
- docs/src/pages/components/Barcharts/AndroidBarChartPage.js
- docs/src/pages/components/SectionList/SectionListPage.js
- docs/src/pages/components/Text/iOSText.mdx
- jsconfig.json
- package-lock.json
- package.json
> [BPK-4324] improve docs components paths

- docs/src/constants/redirect-routes.js
- docs/src/constants/routes.js
- docs/src/pages/components/Alignment/WebAlignmentPage.js
The routes removed in this PR are now auto-generated, so are redundant duplicates.
> [NO-JIRA] Clean up redundant routes

- docs/src/pages/components/TouchableNativeFeedback/NativeTouchableNativeFeedbackPage.js
- docs/src/pages/components/TouchableOverlay/NativeTouchableOverlayPage.js
> Fix overlay broken links

- babel.config.js
- docs/src/pages/components/Overlay/WebOverlayPage.js
- webpack.config.babel.js
> [NO-JIRA] Update license headers 2021

- docs/src/pages/components/BottomSheet/AndroidBottomSheet.mdx
- docs/src/pages/components/BottomSheet/BottomSheetPage.js
> Added Android BottomSheet docs

- docs/src/pages/components/Sliders/SlidersPage.js
- docs/src/pages/components/Sliders/WebSlidersPage.mdx
- package-lock.json
- package.json
> [BPK-3973] Migrate web slider page

- docs/src/pages/components/Map/IOSMap.mdx
- docs/src/pages/components/Map/MapPage.js
> [BPK-4355] Add iOS map marker page

- docs/src/static-pages/colour.mdx
> Update colours usage

- docs/src/pages/components/Link/WebLinksPage.js
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/main/CONTRIBUTING.md)
> [BPK-3615]: Add accessibility Dos and Don'ts for BpkLink

- docs/src/pages/components/Switch/WebSwitchPage.js
> [NO-JIRA] Update switch usage advice

- docs/src/layouts/links.js
- docs/src/pages/components/Map/AndroidMap.mdx
- docs/src/pages/components/Map/MapPage.js
- docs/src/pages/components/RadioButton/AndroidRadioButton.mdx
- docs/src/pages/components/RadioButton/RadioButtonPage.js
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/main/CONTRIBUTING.md)
> [skip ci] Update submodules

- docs/src/components/Color/ColorChart.js
> No jira fix colour contrast eq geq

- docs/src/pages/components/HorizontalNav/WebHorizontalNav.mdx
> [NO-JIRA] Use PresentationBlock darkBackground

- docs/src/layouts/links.js
- docs/src/pages/components/Nudger/IOSNudger.mdx
- docs/src/pages/components/Nudger/NudgerPage.js
Waiting on https://github.com/Skyscanner/backpack-ios/pull/942
> [KOA-4479] Add iOS nudger page

- docs/src/pages/components/Card/WebCard.mdx
- package-lock.json
- package.json
> [KOA-4473] Update card page

- CONTRIBUTING.md
> [KOA-4557] Remove reference to web submodule from setup guide

- docs/src/layouts/links.js
- docs/src/pages/components/Nudger/AndroidNudger.mdx
- docs/src/pages/components/Nudger/NudgerPage.js
Added the docs page for the Android nudger
> KOA-4536 Add Android nudger to docs

- dangerfile.js
Added a check to see if the licensing information is up to date. This only checks modified files, but whenever the first PR is opened in a given year that modifies a file with a licensing header we'll get an error.
> [KOA-4571] Add danger check for current licensing information

- docs/src/layouts/links.js
- docs/src/pages/components/Sliders/AndroidSlidersPage.mdx
- docs/src/pages/components/Sliders/SlidersPage.js
> KOA-4477 Add Android slider docs page

- package-lock.json
- package.json
> Automated upgrade of Backpack dependencies

- docs/src/static-pages/principles.mdx
> Fixing A11y docs link

- docs/src/pages/components/Calendar/AndroidCalendar.mdx
> Add bpk calendar 2 docs

- docs/src/layouts/links.js
- docs/src/pages/components/Button/ButtonPage.js
- docs/src/pages/components/Button/ComposeButton.mdx
- docs/src/pages/components/Card/CardPage.js
- docs/src/pages/components/Card/ComposeCard.mdx
> Added Card and Button Compose docs.

- docs/src/pages/components/Button/AndroidButton.mdx
> Updating button page for Android to fix non existing outline buttons

- docs/src/components/DocsPageWrapper/DocsPageWrapper.js
- docs/src/components/PageSearch/PageSearch.js
- docs/src/layouts/SideNavLayout/NavListFilter.js
> Updated Compose labels.

- docs/src/pages/components/Button/WebButtonPage.mdx
Updating docs page to add new button types
Remove non existing outline button type (causing a page crash)
Cleaned up unused imports to reduce bundle size
> [no jira]: Update Button docs to latest types and fix crash

- docs/src/pages/components/Button/AndroidButton.mdx
- docs/src/pages/components/Button/ComposeButton.mdx
Updated based on the latest button changes
> KOA-5024 Update android button docs

- docs/src/pages/components/Button/WebButtonPage.mdx
> [KOA-5023] Update backpack buttons examples

- docs/src/components/DocsPageWrapper/DocsPageWrapper.js
- docs/src/components/MarkdownPage/AdditionalLinks.js
- docs/src/components/PageSearch/PageSearch.js
- docs/src/layouts/SideNavLayout/NavListFilter.js
> setting up docs for SwiftUI

- docs/src/layouts/links.js
- docs/src/pages/components/Button/ButtonPage.js
- docs/src/pages/components/Button/SwiftUIButtonPage.mdx
- docs/src/pages/components/Card/CardPage.js
- docs/src/pages/components/Card/SwiftUICard.mdx
Add documentation pages for BPKCard and BPKButton
> Update SwiftUI docs for BPKCard/BPKButton

- docs/src/static-pages/typography.mdx
> Update typography guidelines page

- docs/src/pages/components/Rating/WebRating.mdx
- docs/src/themeableAttributes.js
> [no jira]: Updating Web submodule

- docs/src/layouts/links.js
- docs/src/pages/components/Button/ComposeButton.mdx
- docs/src/pages/components/Checkbox/CheckboxPage.js
- docs/src/pages/components/Checkbox/ComposeCheckbox.mdx
- docs/src/pages/components/Dialogs/ComposeDialog.mdx
- docs/src/pages/components/Dialogs/DialogsPage.js
- docs/src/pages/components/Panel/ComposePanel.mdx
- docs/src/pages/components/Panel/PanelPage.js
- docs/src/pages/components/RadioButton/ComposeRadioButton.mdx
- docs/src/pages/components/RadioButton/RadioButtonPage.js
- docs/src/pages/components/Switch/ComposeSwitch.mdx
- docs/src/pages/components/Switch/SwitchPage.js
> Add docs for new compose components

- docs/src/static-pages/layout-grids.mdx
> [NO-JIRA] Remove Figma embed from layout grids page

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/components/FloatingNotification/FloatingNotificationPage.js
- docs/src/pages/components/FloatingNotification/WebFloatingNotification.mdx
- docs/src/pages/components/FloatingNotification/index.js
- docs/src/routes/Routes.js
[ST-4384](https://gojira.skyscanner.net/browse/ST-4384)
Docs for the newly created `bpk-component-floating-notification` as part of Backpack#[2460](https://github.com/Skyscanner/backpack/pull/2460).
**Note:** .mdx files don't seem to support components with hooks, so for now `<iframe>` is used to display examples
- Added `bpk-component-floating-notification` to docs
- Added relevant links in necessary files
> [ST-4384] Added docs for `bpk-component-floating-notification`

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/components/SplitInput/SplitInputPage.js
- docs/src/pages/components/SplitInput/WebSplitInput.mdx
- docs/src/pages/components/SplitInput/index.js
- docs/src/routes/Routes.js
> [NO JIRA] Add split input component page

- docs/src/pages/components/Price/WebPrice.mdx
- docs/src/pages/components/Tickets/WebTicketsPage.mdx
Updating Backpack submodule following the release and updating examples that have changed
> Update Backpack submodule and examples

- docs/src/static-pages/layout-grids.mdx
> [NO JIRA] Add breakpoints scale in rems

- docs/src/layouts/links.js
- docs/src/pages/components/Fieldsets/ComposeFieldsets.mdx
- docs/src/pages/components/Fieldsets/FieldsetsPage.js
- docs/src/pages/components/HorizontalNav/ComposeHorizontalNav.mdx
- docs/src/pages/components/HorizontalNav/HorizontalNavPage.js
- docs/src/pages/components/TextInput/ComposeTextInput.mdx
- docs/src/pages/components/TextInput/TextInputPage.js
> Update Android docs

- docs/src/pages/components/Badge/WebBadgePage.mdx
- docs/src/pages/components/BannerAlert/WebBannerAlertPage.mdx
- docs/src/pages/components/Barcharts/WebBarchartsPage.mdx
- docs/src/pages/components/Button/WebButtonPage.mdx
- docs/src/pages/components/Calendar/WebCalendar.mdx
- docs/src/pages/components/Code/WebCode.mdx
- docs/src/pages/components/RadioButton/WebRadioButton.mdx
- docs/src/pages/components/ScrollableCalendar/WebScrollableCalendar.mdx
- docs/src/pages/components/Select/WebSelect.mdx
- docs/src/pages/components/Sliders/WebSlidersPage.mdx
- docs/src/pages/components/Spinner/WebSpinner.mdx
- docs/src/pages/components/SplitInput/WebSplitInput.mdx
- docs/src/pages/components/StarRating/WebStarRating.mdx
- docs/src/pages/components/Switch/WebSwitch.mdx
- docs/src/themeableAttributes.js
> [KOA-4943] Update web examples

- docs/src/layouts/links.js
- docs/src/pages/components/Chips/IOSChip.mdx
- docs/src/pages/components/HorizontalNav/IOSHorizontalNav.mdx
- docs/src/pages/components/Skeleton/IOSSkeletonPage.mdx
- docs/src/pages/components/Skeleton/SkeletonPage.js
- docs/src/pages/components/Skeleton/SwiftUISkeletonPage.mdx
- docs/src/pages/components/Spinner/AndroidSpinner.mdx
- Add Skeleton iOS guidance.
- Add Skeleton SwiftUI guidance.
[Skeleton _ Backpack.pdf](https://github.com/Skyscanner/backpack-docs/files/9580418/Skeleton._.Backpack.pdf)
> Update skeleton docs - iOS, SwiftUI

- .github/dependabot.yml
- .github/workflows/ci.yml
Upgrades Actions to the latest
Includes actions in dependabot config for bumping
> No jira upgrade actions

- docs/src/pages/components/Badge/WebBadgePage.mdx
- docs/src/pages/components/Chips/WebChip.mdx
> Add Brand badge example

- docs/src/pages/components/FloatingNotification/WebFloatingNotification.mdx
It currently shows this because its not a story that exists!
> Remove non existing example for floating nav

- docs/src/constants/routes.js
- docs/src/layouts/links.js
- docs/src/pages/components/ContentCards/ContentCardsPage.js
- docs/src/pages/components/ContentCards/WebContentCards.mdx
- docs/src/pages/components/ContentCards/index.js
- docs/src/routes/Routes.js
- jsconfig.json
- webpack.config.babel.js
This PR updates the `backpack-docs` with the `content-cards` component that was recently added to Backpack in [this PR](https://github.com/Skyscanner/backpack/pull/2527/).
- JIRA ticket: https://gojira.skyscanner.net/browse/NEUT-638
> [NEUT-638] [WIP] Add BpkContentCards docs to backpack-docs

- docs/src/pages/components/Card/WebCard.mdx
> [BD-6566] Add BpkDividedCard doc

- CONTRIBUTING.md
> Update Contributing guide to clarify how to update submodules with docs

- docs/src/components/DocsPageWrapper/DocsPageWrapper.js
- docs/src/components/MarkdownPage/MarkdownPage.js
- docs/src/pages/components/Overlay/WebOverlay.mdx
Updates Backpack submodule and makes changes to align with recent changes
- Removed use of the `BpkContentContainer` as this is no longer a component
- Updated the `BpkOverlay` examples to use new examples and prevents page crashing
> [NO JIRA]: Update Backpack submodule with new changes
