Skyscanner/backpack-docs

package-lock.json

This changes all Backpack dependencies in the lockfile to be bundled. From what I can tell from reading npm docs, this is what we want. 
I think the file got messed up when people did `npm install` **before cloning submodules**, as it then reverts to the registry or something I guess?
Clone this repo, **with submodules**:
```
git clone --recursive git@github.com:Skyscanner/backpack-docs.git
```
Install deps:
```
npm i
```
If all is well, run the site:
```
npm start
```
If everything is 👌you'll see the docs site after a while.

[BPK-2744] Improve the lockfile

---

docs/src/pages/WebRatingPage/WebRatingPage.js

The high/medium/low appearances are outside of user control and I think the current phrasing could give people the impression that this isn't the case, so I've made it more explicit that it isn't a userland concern.

[No JIRA] Rephrase rating docs slightly

---

docs/src/layouts/links.js
docs/src/pages/FormsPage/FormsPage.js
docs/src/pages/TextViewPage/TextViewPage.js
docs/src/pages/WebTextAreaPage/WebTextAreaPage.js
docs/src/pages/WebTextAreaPage/index.js

[BPK-2693] Split out text-area page

---

docs/src/pages/HomePage/HomePage.js

The icon was pointed out by Will to be bigger than the design, so we remove the `iconWidth` property to make it sized down to the correct size. 
This property was left over from the previous icon and implementation in the old site
Before 
After

Fixing guidelines icon size to be smaller

---

docs/src/layouts/DefaultLayout/default-layout.scss
docs/src/layouts/SideNavLayout/NavList.scss
docs/src/layouts/SideNavLayout/SectionsList.scss
docs/src/layouts/SideNavLayout/Sidebar.scss
docs/src/layouts/SideNavLayout/_common.scss

This aligns colours on the homepage and sidebar to match the new designs as seen below
Homepage background colour:
Navigation sidebar:
Before:
After:

Colour updates

---

docs/src/pages/BackpackReactScriptsPage/BackpackReactScriptsPage.js

This PR upgrades the instructions to match the BRS instructions.
Before:
After:

Updating BRS usage instructions to match BRS

---

docs/src/components/PageSearch/PageSearch.js
docs/src/layouts/SideNavLayout/NavList.js

This was breaking before when using the mouse to click in the suggestions because the `value` provided to the autosuggest input was null.

[NO-JIRA] Fix navbar search box

---

docs/src/pages/IOSBadgePage/IOSBadgePage.js
docs/src/pages/IOSBottomSheetPage/IOSBottomSheetPage.js
docs/src/pages/IOSButtonPage/IOSButtonPage.js
docs/src/pages/IOSCalendarPage/IOSCalendarPage.js
docs/src/pages/IOSCardPage/IOSCardPage.js
docs/src/pages/IOSChipPage/IOSChipPage.js
docs/src/pages/IOSDialogPage/IOSDialogPage.js
docs/src/pages/IOSFlarePage/IOSFlarePage.js
docs/src/pages/IOSHorizontalNavPage/IOSHorizontalNavPage.js
docs/src/pages/IOSIconPage/IOSIconPage.js
docs/src/pages/IOSNavigationBarPage/IOSNavigationBarPage.js
docs/src/pages/IOSPanelPage/IOSPanelPage.js
docs/src/pages/IOSProgressBarPage/IOSProgressBarPage.js
docs/src/pages/IOSRatingPage/IOSRatingPage.js
docs/src/pages/IOSSpinnerPage/IOSSpinnerPage.js
docs/src/pages/IOSStarRatingPage/IOSStarRatingPage.js
docs/src/pages/IOSSwitchPage/IOSSwitchPage.js
docs/src/pages/IOSTappableLinkLabelPage/IOSTappableLinkLabelPage.js
docs/src/pages/IOSTextInputPage/IOSTextInputPage.js
docs/src/pages/IOSTextPage/IOSTextPage.js
docs/src/pages/IOSTextViewPage/IOSTextViewPage.js
docs/src/pages/IOSToastPage/IOSToastPage.js

Note that https://github.com/Skyscanner/backpack-ios/pull/563/ needs to
be merged before this PR.
To run locally uncomment the submodeule update in the `docs` script and
then run `npm run docs`. You might also have to run `git submodules
update --recursive`.

[No JIRA] New screenshot name convention for iOS

---

docs/src/pages/ColorsPage/ColorChart.js

The current heading style can be misinterpreted as saying that all colours are accessibile on white. Hopefully this makes it clearer.

[NO-JIRA] Make colouor pairing headers less misleading

---

docs/src/pages/AndroidBadgePage/AndroidBadgePage.js
docs/src/pages/AndroidButtonPage/AndroidButtonPage.js
docs/src/pages/AndroidCalendarPage/AndroidCalendarPage.js
docs/src/pages/AndroidCardPage/AndroidCardPage.js
docs/src/pages/AndroidCheckboxPage/AndroidCheckboxPage.js
docs/src/pages/AndroidChipPage/AndroidChipPage.js
docs/src/pages/AndroidDialogPage/AndroidDialogPage.js
docs/src/pages/AndroidFlarePage/AndroidFlarePage.js
docs/src/pages/AndroidFloatingActionButtonPage/AndroidFloatingActionButtonPage.js
docs/src/pages/AndroidHorizontalNavPage/AndroidHorizontalNavPage.js
docs/src/pages/AndroidIconPage/AndroidIconPage.js
docs/src/pages/AndroidLinkPage/AndroidLinkPage.js
docs/src/pages/AndroidNavBarPage/AndroidNavBarPage.js
docs/src/pages/AndroidPanelPage/AndroidPanelPage.js
docs/src/pages/AndroidRatingPage/AndroidRatingPage.js
docs/src/pages/AndroidSnackbarPage/AndroidSnackbarPage.js
docs/src/pages/AndroidSpinnerPage/AndroidSpinnerPage.js
docs/src/pages/AndroidStarRatingInteractivePage/AndroidStarRatingInteractivePage.js
docs/src/pages/AndroidStarRatingPage/AndroidStarRatingPage.js
docs/src/pages/AndroidSwitchPage/AndroidSwitchPage.js
docs/src/pages/AndroidTextFieldPage/AndroidTextFieldPage.js
docs/src/pages/AndroidTextPage/AndroidTextPage.js
docs/src/pages/AndroidTextSpansPage/AndroidTextSpansPage.js
docs/src/pages/AndroidToastPage/AndroidToastPage.js

This PR adds the screenshots for Android Dark mode introduced here: https://github.com/Skyscanner/backpack-android/pull/400
This PR cannot be merged until the above PR is merged and the submodule for Android updated

[BPK-3453]: Add Android DM screenshots

---

docs/src/pages/ColorsPage/ColorsPage.js
docs/src/pages/ColorsPage/colors.js

As consumers will use this page as a resource to know what to use, it makes sense to use the US spelling for ease of use

[No Jira] Change greys to use US spelling

---

docs/src/pages/StatusPage/content/androidStatus.md
docs/src/pages/StatusPage/content/backpackNodeSassStatus.md
docs/src/pages/StatusPage/content/eslintConfigSkyscannerStatus.md
docs/src/pages/StatusPage/content/eslintPluginBackpackStatus.md
docs/src/pages/StatusPage/content/iosStatus.md
docs/src/pages/StatusPage/content/nativeStatus.md
docs/src/pages/StatusPage/content/webStatus.md

Now that we have moved from using Greenkeeper as our dependency manager, this PR removes the Greenkeeper badges and replaces them with Snyk badges for reporting the status

Updating greenkeeper badges

---

docs/src/layouts/links.js

Currently clicking `SassDoc` from search tries to navigate to that page within the docs web app, which results in a blank page. It should instead be navigating to `backpack.github.io/sassdoc` and loading the page in its entirety.
The easiest way to achieve this is to treat it as a link to an external site (which it kinda is anyway).
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINE …

[NO-JIRA] Fix sassdoc search link

---

docs/src/components/DocsPageWrapper/DocsPageWrapper.js
docs/src/pages/IconPage/IconPage.js
docs/src/pages/IconsDesignPage/IconDesignPage.js
docs/src/pages/IconsDesignPage/index.js
docs/src/pages/WebIconsPage/IconsPage.js

The purpose of this PR is to add the ability for a design tab for the icons page to hold the list of icons that consumers can use.
- DocsPageWrapper.js - now includes a platform query `design` this will **future proof** us should we want to add design tabs for components or other pages in the future. By default the page will try to select the `design` tab first but if not available will navigate the correct page for the component
- Added `IconsDesignPage` that now holds the icon list and search functionality fields
- Removed icon list and search field from `WebIconsPage` as this is no longer required here.

[BPK-3734]: Add design tab for icons

---

.dependabot/config.yml

This PR adds the dependabot config as per the documentation here: https://dependabot.com/docs/config-file/
So that it doesn't go crazy and update all our bpk dependencies to the non CSS versions as it doesn't look like its currently supported feature - this config ignores all these updates using the `*` operator.

Adding dependabot config to exclude bpk updates

---

docs/src/pages/GraphicDevicesPage/GraphicDevicesPage.js

This PR fixes the names that are displayed below each of the graphic device examples as they were all the same which is incorrect as they aren't representative of what they are, so this corrects them as per the official guidelines.
Before:
After:

[NO JIRA]: Correcting graphic devices titles

---

docs/src/pages/ColorsPage/ColorsPage.js
docs/src/pages/ColorsPage/darkModeColors.js

[BPKR-141] Add dark mode colours to docs

---

docs/src/pages/IOSChipPage/IOSChipPage.js

[BPK-3839] Add chip icons screenshots to iOS page

---

docs/src/layouts/SideNavLayout/NavListFilter.scss

Added 2px margin on both top and bottom of the radio buttons
Current:
New:

[BPK-4093]: Fixed radio spacing

---

docs/src/pages/AutosuggestPage/AutosuggestPage.js

As you can see at https://backpack.github.io/components/autosuggest/?platform=web, clicking on any of the form labels selects the first input as the IDs are not unique.
The mechanism we used before for unique IDs was neat but didn't work, so I've opted for a more verbose approach.

[NO-JIRA] Fix autosuggest example id's

---

docs/src/components/ComponentPage/AndroidComponentPage.js
docs/src/components/ComponentPage/IOSComponentPage.js
docs/src/components/ComponentPage/NativeComponentPage.js
docs/src/components/ComponentPage/WebComponentPage.js
docs/src/pages/AccordionsPage/AccordionsPage.js
docs/src/pages/AlertPage/AlertPage.js
docs/src/pages/AlignmentPage/AlignmentPage.js
docs/src/pages/AndroidBarChartPage/AndroidBarChartPage.js
docs/src/pages/AndroidBottomNavPage/AndroidBottomNavPage.js
docs/src/pages/AndroidButtonPage/AndroidButtonPage.js
docs/src/pages/AndroidCalendarPage/AndroidCalendarPage.js
docs/src/pages/AndroidCardPage/AndroidCardPage.js
docs/src/pages/AndroidCheckboxPage/AndroidCheckboxPage.js
docs/src/pages/AndroidChipPage/AndroidChipPage.js
docs/src/pages/AndroidDialogPage/AndroidDialogPage.js
docs/src/pages/AndroidFlarePage/AndroidFlarePage.js
docs/src/pages/AndroidFloatingActionButtonPage/AndroidFloatingActionButtonPage.js
docs/src/pages/AndroidHorizontalNavPage/AndroidHorizontalNavPage.js
docs/src/pages/AndroidIconPage/AndroidIconPage.js
docs/src/pages/AndroidNavBarPage/AndroidNavBarPage.js
docs/src/pages/AndroidPanelPage/AndroidPanelPage.js
docs/src/pages/AndroidRatingPage/AndroidRatingPage.js
docs/src/pages/AndroidSnackbarPage/AndroidSnackbarPage.js
docs/src/pages/AndroidSpinnerPage/AndroidSpinnerPage.js
docs/src/pages/AndroidStarRatingPage/AndroidStarRatingPage.js
docs/src/pages/AndroidSwitchPage/AndroidSwitchPage.js
docs/src/pages/AndroidTextFieldPage/AndroidTextFieldPage.js
docs/src/pages/AndroidTextPage/AndroidTextPage.js
docs/src/pages/AndroidThemingPage/AndroidThemingPage.js

Also migrated web accordion and alignment pages. Basically all pages beginning in `A`.

[BPK-4141] Migrate Android pages to use AndroidComponentPage

---

docs/src/components/ColorSwatch/ColorSwatch.js
docs/src/components/ColorSwatch/DynamicColorSwatch.js
docs/src/components/GuidelinesBuilder/GuidelinesPageBuilder.js
docs/src/components/HeroSection/HeroSection.js
docs/src/components/PageHead/PageHead.js
docs/src/pages/HorizontalGridPage/HorizontalGridPage.js
docs/src/pages/NativeTouchableNativeFeedbackPage/NativeTouchableNativeFeedbackPage.js
docs/src/pages/NativeTouchableOverlayPage/NativeTouchableOverlayPage.js
docs/src/pages/TypographyPage/FontFace.js
docs/src/pages/TypographyPage/TypeScale.js
docs/src/pages/TypographyPage/font-face.scss
docs/src/pages/TypographyPage/type-scale.scss

Since we deprecated the `bold` prop this PR updates it to the latest version and removes instances of it and aligns it to the correct standards

[NO JIRA]: Updating BpkText bold references

---

.github/dependabot.yml

As Dependabot does not natively support grouping of dependencies (yet) disabling the updating of Backpack components post release from the main repo to stop having multiple PRs to bump all Backpack packages.
There will be a separate process that is responsible for handling the group bumping as part of the release process.

[no-jira]: Disable dependabot for bpk deps

---

.github/dependabot.yml

Looked into the Dependabot config and here's what I've found out:
- We can't currently make it ignore patches, like we wanted
- But we can at least make it ignore indirect dependencies (deps of deps)
I like the idea of making it ignore indirects, because that's how a human would do it — we only manage the deps explicitly defined in our package.json, we don't generally upgrade deps of deps (security fixes notwithstanding), so I made it do that.
As with all of these, we won't know the full effect until we try it out and see how it performs.

[No Jira] Make Dependabot only handle direct dependencies

---

docs/src/template.js

I think setting `og:title` is preventing shared links from using the title set by Helmet. As a result, a preview for http://backpack.github.io/components/section-list/?platform=web will say `Backpack` instead of `Section list | Backpack`.
By removing `og:title` it will (hopefully) fallback to the title set by Helmet.

[NO-JIRA] Remove og:title

---

docs/src/components/DocsPageBuilder/ComponentScreenshots.scss
docs/src/pages/NativeChipsPage/NativeChipsPage.js

I also updated the screenshots CSS to make it look good when more than two screenshots are displayed for an example. You can see the result of it in the screenshot.

[BPK-4242] Docs for updated RN chip component

---

docs/src/layouts/links.js
docs/src/pages/IOSOverlayPage/IOSOverlayPage.js
docs/src/pages/IOSOverlayPage/index.js

Forgot to do this before, so here it is

[NO-JIRA] Add overlay iOS docs

---

docs/src/constants/generated/routes.js
scripts/build-process/generate-pages-from-markdown.js

Will make writing the guide easier. I know it's not perfect atm, e.g. it could use a link to the new contributing guidelines but we can add that once we have them.

[BPK-4275] Add edit links to auto generated pages

---

docs/src/components/DocsPageBuilder/BpkMarkdownRenderer.scss

For now I've just changed the logic we're using in the CSS.
In the future we may want to add a plugin to the Markdown renderer so that we can specify extra props in our files. Jekyll supports this, so on my blog I can do this to add a custom class:
```
```
But this is good for now.

[No Jira] Fix images that were too large

---

docs/src/static-pages/status.md

Removed link from Travis as its no longer used.
Updated links to go directly to each build
Updated LICENCE link as it went to a dead page

Updating BRS status links

---

docs/src/constants/routes.js
docs/src/layouts/SideNavLayout/SideNavLayout.js
docs/src/layouts/SideNavLayout/SideNavLayout.scss
docs/src/layouts/links.js
docs/src/pages/components/SkipLink/SkipLinkPage.js
docs/src/pages/components/SkipLink/WebSkipLinkPage.js
docs/src/pages/components/SkipLink/index.js
docs/src/pages/components/SkipLink/skip-link-page.scss
docs/src/routes/Routes.js
docs/src/static-pages/developer-accessibility.mdx
package-lock.json
package.json

I also added one at the top of the doc page:

[BPK-3976] Add skip-link docs

---

docs/src/index.js
docs/src/meta.js
docs/src/template.js

Previously our document head contained two sets of meta tags and we were relying on sites to take the latest ones. This works on Twitter but not Slack.
This PR puts our meta tags into `react-helmet` so they can be overridden. See below for a screenshot of the animation page's meta tags. Note how there is only one set of `og:description` and `og:title` now. This means that Slack should correctly preview our pages.

[No Jira] Fix metadata on Slack

---

docs/src/pages/components/Icon/DesignIconPage.js

I also removed this:
> Both are pixel-snapped for clarity at the intended usage sizes.
I have no idea what this means, so it's unlikely consumers will.

[BPK-4332] Rephrase icons page

---

docs/src/index.js

Fixed an issue where Relative was not loading on the docs site in Safari by opting the docs site into the font loading from the `bpk-stylesheets/font` import. As some time ago font loading was removed from `bpk-stylesheet/base` and required opt in to get the fonts
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack/blob/main/CONTRIBUTING.md)

[BPK-4418]: Fixing Relative font loading by opting into font loading from bpk-stylesheets

---

docs/src/components/MDXContent/renderers.js

On prod – where are the code blocks?
This PR – all fixed:

[No Jira] Fix code block display

---

package-lock.json
package.json

I'm relatively confident these aren't used. I ran the docs site locally and it didn't fail to compile, and CI is happy.
I've no idea why the lockfile didn't change here, I did `npm uninstall --save-dev <package>` so I think I did everything correctly.

[No Jira] Remove some unused dependencies

---

.github/workflows/ci.yml

All our dependabot PRs are failing when it comes to the Danger step in CI, which is due to how it has access to the token and uses it - means that this step fails due to the token not working for 'bots'.
This PR excludes the danger step from any PR builds which can be verfied CI passes with this on #957 - https://github.com/Skyscanner/backpack-docs/runs/2325786683?check_suite_focus=true.

[NO JIRA]: Excluding danger from running on dependabot PRs

---

dangerfile.js

Updated the external check to be async and catching an exception to fix the external contribution check. Unlike other repositories it doesn't look like we're reporting the danger status, so this seems to still be working fine with the danger token.

[KOA-4571] Change external check to async function

---

docs/src/components/MarkdownPage/AdditionalLinks.js

With https://github.com/Skyscanner/backpack-android/pull/805 the dokka url changes to support multiple URLs. Update accordingly.

KOA-4722 Update Android dokka url

---

docs/src/pages/components/Calendar/WebCalendar.mdx
docs/src/pages/components/Datepicker/WebDatepicker.mdx

Adding range examples for Calendar and Datepicker.
Currently excluding the Scrollable Calendar due to a visual bug when using ranges which is currently a fix in progress

Adding Range calendar docs examples

---

docs/src/pages/components/Text/AndroidText.mdx

Updated the android text docs screenshots to match the new typescale.

KOA-4827 Update android text docs

---

docs/src/constants/routes.js
docs/src/layouts/links.js
docs/src/pages/components/GraphicPromotion/GraphicPromotionPage.js
docs/src/pages/components/GraphicPromotion/WebGraphicPromotion.mdx
docs/src/pages/components/GraphicPromotion/index.js
docs/src/routes/Routes.js

[ST-4140](https://gojira.skyscanner.net/browse/ST-4140)
Backpack#[2395](https://github.com/Skyscanner/backpack/pull/2395) adds the `bpk-component-graphic-promotion` for web. This PR adds the necessary docs.
- Added `bpk-component-graphic-promotion`
- Added relevant links in necessary files

[ST-4140] Added `bpk-component-graphic-promotion` to docs

---

package.json

Fix issue where installed storybook lib inside Backpack causes a crash when used outside storybook in examples.
Our storybook-utils was created as a way to allow `action` to be used as in storybook and print to storybook when an element is interacted with and then when outside of storybook/the actions lib not installed to fallback to console.log
However because we are using submodules this library would be installed and so the function would think that the lib is available and running in storybook which then when interacted with will crash as it emits a result that can't be consumed as storybook is not running, resulting in a crash

[NO JIRA]: Fix example crashes

---

docs/src/pages/components/Nudger/WebNudger.mdx

We recently removed the outline nudger from Backpack web however I forgot to remove this and update the docs site after removing it! 
This PR fixes that

[no jira]: Fixing Web nudger page after recent component change
